/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Partido extends javax.swing.JFrame {
    private Quiniela q;
    /**
     * Creates new form Partido
     */
    public Partido(Quiniela q) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.q=q;
    }
    public Partido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pContenido = new javax.swing.JPanel();
        lPartido = new javax.swing.JLabel();
        tfNombreEquipos = new javax.swing.JTextField();
        bAceptar = new javax.swing.JButton();
        pAdvertencia = new javax.swing.JPanel();
        lAdvertencia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar nuevo partido");

        pContenido.setLayout(new java.awt.BorderLayout());

        lPartido.setText("Partido: ");
        pContenido.add(lPartido, java.awt.BorderLayout.WEST);
        pContenido.add(tfNombreEquipos, java.awt.BorderLayout.CENTER);

        bAceptar.setText("Aceptar");
        bAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAceptarActionPerformed(evt);
            }
        });
        pContenido.add(bAceptar, java.awt.BorderLayout.EAST);

        pAdvertencia.setLayout(new java.awt.BorderLayout());

        lAdvertencia.setText("Advertencia: ventana de subprograma");
        pAdvertencia.add(lAdvertencia, java.awt.BorderLayout.CENTER);

        pContenido.add(pAdvertencia, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pContenido, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAceptarActionPerformed
        String nombre=tfNombreEquipos.getText();
        q.agregarPartido(nombre);
        tfNombreEquipos.setText("");
        
    }//GEN-LAST:event_bAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAceptar;
    private javax.swing.JLabel lAdvertencia;
    private javax.swing.JLabel lPartido;
    private javax.swing.JPanel pAdvertencia;
    private javax.swing.JPanel pContenido;
    private javax.swing.JTextField tfNombreEquipos;
    // End of variables declaration//GEN-END:variables
}
