
import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class Quiniela extends javax.swing.JFrame {

    
    private DefaultListModel modelovacio;
    
    
    
    /**
     * Agrega el texto pasado en la otra ventana al text area
     * @param partido equipos del partido
     */
    public void agregarPartido(String partido)
    {
        modelovacio= new DefaultListModel();
        for (int i = 0; i < listPartidos.getModel().getSize(); i++) 
        {
            modelovacio.addElement(listPartidos.getModel().getElementAt(i));
            
        }
        modelovacio.addElement(partido);
        listPartidos.setModel(modelovacio);
    }
    
    public void eliminarPartido(int n)
    {
        listPartidos.remove(n);
    }
    /**
     * Creates new form Quiniela
     */
    public Quiniela() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pOrdenacionTitulo = new javax.swing.JPanel();
        pTitulo = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        pCabeceras = new javax.swing.JPanel();
        lPartidos = new javax.swing.JLabel();
        lResultados = new javax.swing.JLabel();
        pContenido = new javax.swing.JPanel();
        pPartidos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listPartidos = new javax.swing.JList<>();
        pResultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listResultados = new javax.swing.JList<>();
        pBotones = new javax.swing.JPanel();
        bNuevo = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bRealizar = new javax.swing.JButton();
        bResetear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pOrdenacionTitulo.setLayout(new java.awt.BorderLayout());

        lTitulo.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        lTitulo.setForeground(new java.awt.Color(255, 0, 0));
        lTitulo.setText("Quiniela");
        pTitulo.add(lTitulo);

        pOrdenacionTitulo.add(pTitulo, java.awt.BorderLayout.PAGE_START);

        pCabeceras.setLayout(new java.awt.GridLayout(1, 2));

        lPartidos.setText("Partidos");
        pCabeceras.add(lPartidos);

        lResultados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lResultados.setText("Resultados");
        pCabeceras.add(lResultados);

        pOrdenacionTitulo.add(pCabeceras, java.awt.BorderLayout.CENTER);

        getContentPane().add(pOrdenacionTitulo, java.awt.BorderLayout.NORTH);

        pContenido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pContenido.setLayout(new java.awt.BorderLayout());

        pPartidos.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane2.setViewportView(listPartidos);

        pPartidos.add(jScrollPane2);

        pContenido.add(pPartidos, java.awt.BorderLayout.LINE_START);

        pResultados.setLayout(new java.awt.GridLayout(1, 0));

        jScrollPane1.setViewportView(listResultados);

        pResultados.add(jScrollPane1);

        pContenido.add(pResultados, java.awt.BorderLayout.LINE_END);

        pBotones.setLayout(new java.awt.GridLayout(4, 0));

        bNuevo.setText("Nuevo");
        bNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoActionPerformed(evt);
            }
        });
        pBotones.add(bNuevo);

        bEliminar.setText("Eliminar");
        bEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarActionPerformed(evt);
            }
        });
        pBotones.add(bEliminar);

        bRealizar.setText("Realizar quiniela");
        bRealizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRealizarActionPerformed(evt);
            }
        });
        pBotones.add(bRealizar);

        bResetear.setText("Resetear");
        bResetear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetearActionPerformed(evt);
            }
        });
        pBotones.add(bResetear);

        pContenido.add(pBotones, java.awt.BorderLayout.CENTER);

        getContentPane().add(pContenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoActionPerformed
        
        Partido p=new Partido(this);
        
        p.setSize(300, 100);
        
        p.setVisible(true);
        
        
    }//GEN-LAST:event_bNuevoActionPerformed

    private void bResetearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetearActionPerformed
        DefaultListModel modelo=new DefaultListModel();
        
        listResultados.setModel(modelo);
    }//GEN-LAST:event_bResetearActionPerformed

    private void bEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarActionPerformed
        DefaultListModel modelo= (DefaultListModel) listPartidos.getModel();
        
        int n=listPartidos.getSelectedIndex();
        modelo.remove(n);
        
        
        
        
        
    }//GEN-LAST:event_bEliminarActionPerformed

    private void bRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRealizarActionPerformed
        Random aleatorio= new Random();
        
        
        DefaultListModel modelo=new DefaultListModel();
        DefaultListModel modelo2= (DefaultListModel) listPartidos.getModel();
        
        for (int i = 0; i < modelo2.size(); i++) 
        {
            int ale=aleatorio.nextInt(3-1)+1;
            String resultado="";

            if(ale==1)
            {
                resultado="X";
            }
            else if(ale==2)
            {
                resultado="1";
            }
            else if(ale==3)
            {
                resultado="2";
            }
            String elemento=modelo2.get(i).toString()+"--> "+resultado;
            modelo.addElement(elemento);
            
        }
        listResultados.setModel(modelo);
        listPartidos.setModel(new DefaultListModel());
        
        
        
    }//GEN-LAST:event_bRealizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiniela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiniela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JButton bRealizar;
    private javax.swing.JButton bResetear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lPartidos;
    private javax.swing.JLabel lResultados;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JList<String> listPartidos;
    private javax.swing.JList<String> listResultados;
    private javax.swing.JPanel pBotones;
    private javax.swing.JPanel pCabeceras;
    private javax.swing.JPanel pContenido;
    private javax.swing.JPanel pOrdenacionTitulo;
    private javax.swing.JPanel pPartidos;
    private javax.swing.JPanel pResultados;
    private javax.swing.JPanel pTitulo;
    // End of variables declaration//GEN-END:variables
}
